### ISSUE TITLE
new class().exec()の形ではなく function() の形にしたい

### ISSUE THREAD

**Issue by TakuKobayashi** [antyuntyuntyun/qiita-cli#28]
Qiitaへの投稿、執筆管理をGithubで管理し、自動的に投稿できるようにしたく思い、その中で `qiita-cli` を見つけました。
大変すばらしいプロジェクト(ライブラリ)だと思います。ぜひこれからも使わせていただきたく思い、
つきましては私も開発を進めさせていただければと思います。

現在、以下のように各種処理を `class` を newして実行している形からシンプルに `function` で実行する形に直した方がすっきりしていいのではないかと思います

現在
```typescript
new accessTokenInitialize().exec()
```

変更後
```typescript
accessTokenInitialize()
```

**Comment by antyuntyuntyun** [comment]
@TakuKobayashi
見つけて頂きありがとうございます！是非開発進めるのにご助力頂ければと思います。
昔に書いたコードで全然メンテできてないのですが、おっしゃる通り関数呼び出しで実行するのが良いのはその通りだと思います。（PR頂けると大変助かります！）
その他気になる点や改修したほうが良い点たくさんあると思うので、随時ご指摘ください！

**Comment by antyuntyuntyun** [comment]
もうPR頂いてましたね、失礼しました

**Comment by TakuKobayashi** [comment]
@antyuntyuntyun 
ありがとうございます!!
この後、いくつかissueを立てさせていただくのと、またそれに応じたPRを出させていただくと思います。
よろしくお願いします。
