### ISSUE TITLE
commanderの導入

### ISSUE THREAD

**Issue by TakuKobayashi** [antyuntyuntyun/qiita-cli#30]
`commander` というNodeJSでのCLIの開発にて広く使用されているライブラリがあります。(claspなどのメジャーなライブラリにも使用されています)
https://github.com/tj/commander.js

現状、
```typescript
if (process.argv[2] === '--help' || process.argv[2] === '-h') {
}
```
のように引数の特定箇所を見て判別しています。
`commander` では各種のエッジケースなども含めてカバーしてくれているので `commander` を導入した形に変更できたらいいなと思います

**Comment by antyuntyuntyun** [comment]
開発初期に `commander` 入れようとしたのですが、当時TypeScript環境設定していた時に確かバージョン競合か何かでうまく導入できず頓挫して諦めた記憶があります。
導入したいです！

**Comment by TakuKobayashi** [comment]
@antyuntyuntyun 続きましてこちらのPRを出しました。すみませんがご確認のほどよろしくお願いします。

**Comment by antyuntyuntyun** [comment]
@TakuKobayashi
PR確認してマージさせていただきました!

**Comment by antyuntyuntyun** [comment]
:+1:
