### ISSUE TITLE
--token -t オプションでQiitaのaccessTokenをつけられるようにしたい

### ISSUE THREAD

**Issue by TakuKobayashi** [antyuntyuntyun/qiita-cli#31]
CLIを実行するにあたり現在
```
qiita init
```
を実行して、`~/.qiita/qiita.json` に `accessToken` を記録しなければなりません。
これだと [Github Actions](https://github.co.jp/features/actions) などの CI 環境で使用するにはちょっと使いにくいなと思いましたので、`--token -t` オプションを追加して `accessToken` を設定することでも実行できるようにできたらなと思います
コマンド例としては以下のような形になります。

```
qiita pull:article --token [AccessToken]
```

**Comment by antyuntyuntyun** [comment]
`zenn-cli` で出来るような、特定レポジトリと記事を同期させる処理を考えるとおっしゃる通りCI環境適用の考慮が必要ですね!
